### ISSUE TITLE
Shopping cart is slow in general (add, update, delete)

### ISSUE THREAD

**Issue by zebercut** [SAP/cloud-commerce-spartacus-storefront#3069] opened 2019-06-11 20:28 UTC
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details
- Spartacus:  Beta
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/
- Browser: 
- OS: 
- Device: 

## Steps to Reproduce
Adding, removing and updating items to the shopping cart is slow. If you add 10 items, you see a delay of 3 -4 seconds to get the updated result.
This is not really accepted in a commerce solution.

**Comment by Xymmer** [comment] 2019-06-11 22:45
dupe of #3012

**Closed** 2019-06-11 22:48 UTC
Labels: closed/duplicate, type/bug
