### ISSUE TITLE
Delivery modes are loaded as soon as application starts

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#3243] opened 2019-06-18 14:52 UTC
See this image:
<img width="1440" alt="Screen Shot 2019-06-18 at 10 47 53" src="https://user-images.githubusercontent.com/11561723/59694562-d4b1ac80-91b6-11e9-9efc-89269d231ddb.png">

1. We shouldn't try to fetch delivery modes when a user is not on that checkout step
2. There's `undefined` in the URL, after `/carts`: `http://localhost:4300/rest/v2//users/anonymous/carts/undefined/deliverymodes?lang=en&curr=USD`

**Comment by LTiger14** [comment] 2019-06-18 14:59
On refresh the action `LANGUAGE_CHANGE` is dispatched. In `checkout.effect.ts` there is an effect `clearCheckoutMiscsDataOnLanguageChange$` that listen's to it and will dispatch `CheckoutClearMiscsData()` (`CHECKOUT_CLEAR_MISCS_DATA`).

This action is listened to by `reloadSupportedDeliveryModesOnSiteContextChange$` which will in term fire an even to Load Supported Delivery Modes.

**Comment by RadhepS** [comment] 2019-06-18 15:00
Most likely caused by this ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3016

**Comment by WeizhengSap** [comment] 2019-06-20 18:30
This was fixed in #3288

**Closed** 2019-06-20 18:46 UTC
Labels: type/bug
