### ISSUE TITLE
[feb8: waiting for backend update] Storefinder view all stores returns an error [dupe of #992?]

### ISSUE THREAD

**Issue by znikola** [SAP/cloud-commerce-spartacus-storefront#1113] opened 2019-01-31 15:46 UTC
Navigating to http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/store-finder/country/JP returns a `404` error:

![screen shot 2019-01-31 at 10 45 10](https://user-images.githubusercontent.com/11561723/52065870-65a82400-2545-11e9-9eda-1b6a41329db1.png)

**Comment by Xymmer** [comment] 2019-01-31 16:53
Depends on Walker PRs in C3PO-1203 being merged

**Comment by Xymmer** [comment] 2019-02-08 14:39
latest status feb8: looks like C3PO-1203 was merged, but there is still OCC PR E2EC-941 not merged yet.

**Comment by Xymmer** [comment] 2019-02-08 14:42
are #1113 and #992 same issue?

**Comment by Matejk00** [comment] 2019-02-11 07:55
@Xymmer it's a dupe of #992

**Closed** 2019-02-13 22:56 UTC
Labels: type/bug, z/storefinder
