### ISSUE TITLE
Component rendering/refresh does not work in SPA

### ISSUE THREAD

**Issue by stepan-aleksandrov** [SAP/cloud-commerce-spartacus-storefront#2085] opened 2019-04-18 15:21 UTC
The smart-edit.service.renderComponent does not render or refresh  a component.
When the component is changed in SmartEdit it calls **renderComponent** with one attribute - the slot id that contains the changed component. But the slot is not refresh. 
Same problem happens with newly added component.

## Environment Details

- Spartacus:  latest
- Browser: Chrome latest

## Steps to Reproduce (Edit)
1. Go to SPA storefront
2. Open any component (ex. Paragraph)
3. Change the data in the component
4. Save
5. Nothing has been changed on storefront (only browser refresh helps)

## Steps to Reproduce (Add)
1. Go to SPA storefront
2. Add new paragraph component on the storefront
4. Save
5. New component is not visible on storefront (only browser refresh helps)

**Comment by WeizhengSap** [comment] 2019-04-23 19:16
I cannot reproduce it on my local. Slot is re-rendered if I add/remove component; and component is also re-rendered if I edit it.

**Comment by WeizhengSap** [comment] 2019-04-23 20:31
I will close this ticket, because Stepan said: When I build smartedit in production mode it starts working.

**Comment by stepan-aleksandrov** [comment] 2019-04-29 19:49
Unfortunately the problem is not related to building the app in production mode.
Now we understand why the rendering works for Wei and does not work for anyone else. When the Redux extension is enabled the rendering on Spartacus side works fine and when it's disabled the rendering stops working. So SPA team should do the following: disable Redux extension and try to debug the reRendering functionality.

**Comment by WeizhengSap** [comment] 2019-05-01 12:40
To QA/code reviewer:
To test this ticket, you need disable the redux extension in browser.
In smartedit, go to homepage. You can edit/add/remove any components. The component should be refreshed automatically

**Closed** 2019-05-01 20:28 UTC
Labels: type/bug, z/smartedit

**Comment by Xymmer** [comment] 2019-05-03 16:51
They are still seeing issues (see https://jira.hybris.com/browse/CMSX-8739) but i'm trying it out

**Comment by KateChuen** [comment] 2019-05-07 17:18
Adding, Editing and Removing a component is rendered properly on the storefront now (with redux extension disabled). Tested with the FAQ page on dev2 server.
