### ISSUE TITLE
DUPE [Xiaomi/Chrome] - Order history details show duplicate status

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3518] opened 2019-07-02 11:34 UTC
ie. Status, In Process, In process...

![image](https://user-images.githubusercontent.com/11735817/60509774-0dc94100-9cce-11e9-875e-6b36b995771f.png)

**Comment by developpeurweb** [comment] 2019-07-02 18:06
This is a dupe of GH-3055

**Closed** 2019-07-03 22:43 UTC
Labels: closed/duplicate, ux
