### ISSUE TITLE
Button styling in personal details page

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3498] opened 2019-07-02 06:50 UTC
No margin/space between buttons in personal details page on the mobile viewport.

Same in update password, update email page.

![storefrontapp marlas now sh_(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/6259079/60490225-671d7a00-9ca6-11e9-94ec-2cc049ffc749.png)

**Comment by Xymmer** [comment] 2019-07-03 22:51
dupe of another ticket

**Closed by Xymmer** 2019-07-03 22:51 UTC
Labels: styling, type/bug
