### ISSUE TITLE
Sometimes Desktop Submenu appears in the middle of the page 

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2242] opened 2019-04-30 18:12 UTC
I cannot figure out how to reproduce this consistently, but in some circumstances the main menu items appear in the middle of the page, not underneath the clicked menu item.

Here is the result...
![SNAG-0008](https://user-images.githubusercontent.com/44620139/56983556-e9c47480-6b51-11e9-8686-d29237a7ef1c.png)

**Comment by Xymmer** [comment] 2019-05-07 14:06
dupe of GH-2014

**Closed by Xymmer** 2019-05-07 14:06 UTC
Labels: closed/duplicate, type/bug
