### ISSUE TITLE
Console errors on shipping address step at checkout

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#888] opened 2019-01-15 08:10 UTC
It might be related to this: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/734
When customer has no any shipping address added yet and want go through the checkout in the console following error appears:

Chrome: 
![image](https://user-images.githubusercontent.com/6259079/51166844-1dcaa100-18a5-11e9-83ad-368c1ba3ca6d.png)
Firefox:
![image](https://user-images.githubusercontent.com/6259079/51166853-2327eb80-18a5-11e9-9cac-a24f4392062c.png)

Found while smoke testing release 2019/01/14 (https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/875)

**Comment by mirkosoft** [comment] 2019-03-01 17:29
Can't reproduce this on chrome and firefox. Seems to be already fixed with below one from the past:
https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/e54f690001706f122ce6300dd32e02bd99a747c8#diff-041fcc65d221974bc92d0a874c5b63bb

Smoke test however, has been performed 3 weeks later. @marlass is it still occurring for you?

**Comment by mirkosoft** [comment] 2019-03-04 17:27
Not sure what version is at the github pages but I can't reproduce this bug over there as well.

**Closed** 2019-03-05 08:15 UTC
Labels: type/bug
