### ISSUE TITLE
Styling of 'remove' button seems wrong

### ISSUE THREAD

**Issue by zebercut** [SAP/cloud-commerce-spartacus-storefront#3060] opened 2019-06-11 19:42 UTC
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  Beta
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/
- Browser: 
- OS: 
- Device: 

## Steps to Reproduce
1. Add a few items to the cart
2. View the cart
3. you see a remove button/link that has some unmatched styling with the rest of the storefront
## Additional Information

![image](https://user-images.githubusercontent.com/6307948/59301378-7a1ccb80-8c5f-11e9-90f0-19373bffa34c.png)

**Comment by Xymmer** [comment] 2019-06-11 22:33
I'm pretty certain it shouldn't be underline unless we point to it, but is there supposed to be a color? Moving to Praetorians board

**Comment by developpeurweb** [comment] 2019-06-17 13:28
@Xymmer this is in fact not really as per mockups, since we removed parts along the way, no uppercase on links, no color on hover, i'm attaching screenshot of the original mockups and style guidelines. Please confirm which one you want.

<img width="1255" alt="Screen Shot 2019-06-17 at 9 12 44 AM" src="https://user-images.githubusercontent.com/15113219/59607856-1de3fc80-90e2-11e9-9507-efdf4a6fc3a3.png">

![Screen Shot 2019-06-17 at 9 13 15 AM](https://user-images.githubusercontent.com/15113219/59607865-22a8b080-90e2-11e9-8a69-c4e2e187ec68.png)

P.S. Couldn't reproduce the grey highlight.

**Comment by Xymmer** [comment] 2019-06-17 15:46
can you make it so the underline is not there until you hover?
and ask to update the style guidelines?

**Comment by developpeurweb** [comment] 2019-06-20 15:03
Link style has been updated.
Manu: can you please sync-up with @Xymmer regarding the update of the style guidelines.

**Comment by Manurod2018** [comment] 2019-06-20 15:46
![Screen Shot 2019-06-20 at 11 15 03 AM](https://user-images.githubusercontent.com/37299626/59862478-dadb9080-9350-11e9-9eca-5730c00a7751.png)

As you can see in the attached screenshot, removing the underline from links will make it difficult for users to visually find the link on the page. 
As part of the accessibility requirements, we are underlining all links, except for the main menu. This helps clearly identifying specific text or actions as links. On hover, the color of the link changes, providing an additional visual cue for focus state.

**Closed** 2019-06-20 18:41 UTC
Labels: type/bug, ux

**Comment by KateChuen** [comment] 2019-06-20 20:16
Tested on dev2. 
Remove button is only underlined when the cursor is on it now.

<img width="1100" alt="Screen Shot 2019-06-20 at 4 10 45 PM" src="https://user-images.githubusercontent.com/45409515/59878495-7501ff80-9376-11e9-8b06-cd51c0b6aa6e.png">

I do find this hard to detect that the Remove button is actually a button on this dialog. Maybe future discussion. 
<img width="804" alt="Screen Shot 2019-06-20 at 4 15 01 PM" src="https://user-images.githubusercontent.com/45409515/59878545-9531be80-9376-11e9-9247-ba801f7314f6.png">

**Comment by Xymmer** [comment] 2019-06-20 20:53
agree but also i find this whole layout needs improvement. when i look at it, my eye goes item-qty-total-remove then to the right. let's leave as is for now and revisit right away after 1.0

**Comment by Manurod2018** [comment] 2019-06-21 14:56
Removing an item was never part of the “Added to Cart” modal, we already have this option on the Cart. Was this intentionally added or is it a mistake? The modal is only to confirm that the product has been successfully added to the cart.
