### ISSUE TITLE
[dupe of #3942] Store finder - find stores pages are not logged in the router

### ISSUE THREAD

**Issue by eliztrinh** [SAP/cloud-commerce-spartacus-storefront#779] opened 2018-12-27 16:05 UTC
For all details, please see https://jira.hybris.com/browse/E2EC-1356
priority: Minor

## Expected Results
All clicking to the next page are logged in the router so when you click back you go to the previous page.

## Observed Results
It takes you back to the very beginning of store finder (before you clicked search button).

## Steps to Reproduce
go to store finder -> find stores -> go to the next page a few times -> click backward button of the browser

it takes you back to the very beginning of store finder (before you clicked search button).

**Comment by Xymmer** [comment] 2019-02-17 13:42
trying to repro but blocked by #1236

**Comment by Xymmer** [comment] 2019-04-08 12:15
don't think this is blocked anymore
pagination is working, and #1236 is more of an improvement

**Comment by Xymmer** [comment] 2019-08-06 11:46
dupe of #3942

**Closed** 2019-08-28 08:39 UTC
Labels: closed/duplicate, storefinder, type/bug
