### ISSUE TITLE
checkout flows e2e tests failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6147] opened 2020-01-20 04:18 UTC
**Environment:** dev-12
**Branch:** feature/e2etests-1905.6

_mobile/checkout/checkout-flow-mobile.e2e-spec.ts_ is failing

**Comment by psmul** [comment] 2020-01-20 13:56
All tests passing as green. Probably there was small block caused by delivery mode which has been fixed here: #6152

**Comment by qjimmy** [comment] 2020-01-20 19:29
**Environment:** dev-12
**Branch:** feature/e2etests-1905.6

The checkout-flow-mobile.e2e-spec.ts test is failing because it can't find a function. See below.

<img width="1088" alt="Screen Shot 2020-01-20 at 2 12 13 PM" src="https://user-images.githubusercontent.com/30666844/72751915-d6997f00-3b8e-11ea-9add-9459ee32773e.png">

![Screen Shot 2020-01-20 at 2 12 40 PM](https://user-images.githubusercontent.com/30666844/72751927-e44f0480-3b8e-11ea-839a-bdc1ec551698.png)

The checkout-as-guest.e2e-spec.ts test is also failing due to the same issue as above

<img width="1088" alt="Screen Shot 2020-01-20 at 2 20 58 PM" src="https://user-images.githubusercontent.com/30666844/72752466-42301c00-3b90-11ea-82c6-eabad7937c5a.png">

**Comment by psmul** [comment] 2020-01-22 09:28
Fix has been applied, however, we should keep in mind that Order history needs to be tested as well. Currently, due to some backend delay in creating order history, test was simply removed.

**Closed by psmul** 2020-01-22 09:28 UTC
Labels: 1.5-e2e, e2e-tests

**Comment by psmul** [comment] 2020-01-22 09:29
QA steps:

- run tests for checkout-flow-mobile.e2e-spec.ts

Expected result:

- tests should pass

**Comment by Matejk00** [comment] 2020-01-24 10:17
Qa done, tests are passing.
