### ISSUE TITLE
In spacceleratoraddon, update banner links to match new routes for Spartacus (they work for Accelerator right now)

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#514] opened 2018-12-03 18:10 UTC
## Environment Details

- Spartacus: develop branch
- Browser: chrome Version 70.0.3538.110 
- OS: MacOS 10.14.1
- Device:
- Other environment details:

## Steps to Reproduce
- Missing pages
-- This product page: http://localhost:4200/Open-Catalogue/Cameras/Webcams/QuickCam-for-Notebooks-Pro/p/479742
--- maybe remove them? Or add an empty page for them?
![missingpage](https://user-images.githubusercontent.com/45409515/49392552-c90c0600-f6fc-11e8-91e3-b81bdceffcbe.png)

**Comment by KateChuen** [comment] 2019-01-09 14:56
**Bug Triage**
The 2 problematic products are the last 2 on the homepage. 
The links are hardcoded and have to be fixed to use the new routing mechanism in the backend.

**Comment by Xymmer** [comment] 2019-01-09 15:04
the new links have to be done in backend, but can't affect accelerator, so must be added to spaccelerator extension

**Comment by Xymmer** [comment] 2019-02-08 16:07
the coding gnomes fixed this one, closing

**Comment by Xymmer** [comment] 2019-02-08 16:20
dupe of #822

**Closed** 2019-03-11 19:55 UTC
Labels: backend, closed/duplicate, epic/backendcmsupdate, refinement needed, type/bug
