### ISSUE TITLE
Check if all y- prefixes were changed to cx- in styling

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#43] opened 2018-10-27 13:06 UTC
Looks like Roman did changes to styling too.

This ticket is to make sure Roman got them all, otherwise move back to PO column.

Github issue to change prefixes in code: #42 
Previous internal ticket: SPA-1220

**Comment by developpeurweb** [comment] 2018-11-05 16:43
This turned out to be a duplicate of issue #42 so we'll keep PR #196 open until #183 is successfully merged.

**Closed** 2018-11-27 13:20 UTC
Labels: epic/yprefix, team/gladiators, ux
