### ISSUE TITLE
clicking on back to top on terms and conditions redirects the user to homepage

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#1441] opened 2019-02-26 15:21 UTC
## Environment Details
* Spartacus: dev branch
* Browser: chrome

## Steps to Reproduce
Add items to cart
Proceed to checkout
On last step of checkout, click on "Terms and Conditions" 
Scroll down
Click on "back to top"

## Observed Results
User gets redirected to the homepage, with url "http://localhost:4200/en/USD/#00"
This error in console:

> ERROR DOMException: Failed to execute 'querySelector' on 'Document': '#00' is not a valid selector.
    at BrowserViewportScroller.push.../../node_modules/@angular/common/fesm5/common.js.BrowserViewportScroller.scrollToAnchor (http://localhost:4200/vendor.js:11580:48)
    at SafeSubscriber._next (http://localhost:4200/vendor.js:81548:44)
    at SafeSubscriber.push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.js:103476:16)
    at SafeSubscriber.push.../../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (http://localhost:4200/vendor.js:103414:22)
    at 

## Expected Results
User should be redirected to the top of the TermsAndConditions page.

**Comment by KateChuen** [comment] 2019-03-12 13:52
Check if this is already fixed, because Tobias has created a ticket about the back not being registered.If not, then fix it. 
Also happens on the FAQ page.

**Comment by Xymmer** [comment] 2019-03-28 16:39
sample data issue. the back to top link is inside the sample t&c i'm pretty sure

**Comment by Zeyber** [comment] 2019-04-24 12:56
Able to replicate issue but HTML for page with "back to top" links comes from backend. May have been updated already but I can't verify this (I'm using an old public api until I have proper access).

**Comment by Platonn** [comment] 2019-07-12 12:43
Duplicate of https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/915

**Closed** 2019-07-16 14:47 UTC
Labels: type/bug
