### ISSUE TITLE
Cart icon too far right (iPad Air Safari vertical)

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3144] opened 2019-06-12 23:40 UTC
(also see #3068)

Seen in iPad Air safari vertical
The cart box is touching the right side of the screen

**Comment by Xymmer** [comment] 2019-06-13 00:10
![IMG_0030](https://user-images.githubusercontent.com/4998145/59394556-12917980-8d4e-11e9-9e85-3bb6847e930b.PNG)

**Comment by developpeurweb** [comment] 2019-06-25 23:08
This is now fixed, breaking point is 767px wide, passing this width mobile view kicks-in, that is ... button changes to square shape and search bar disappears.

![Screen Shot 2019-06-25 at 7 02 54 PM](https://user-images.githubusercontent.com/15113219/60139615-8c792800-977c-11e9-9c7d-b2538955b78b.png)

**Closed** 2019-06-27 22:25 UTC
Labels: type/bug

**Comment by KateChuen** [comment] 2019-06-28 19:44
Saw the issue on mac, with a small viewport of 990x950 on an older build.
Tested the fix on dev19, with same viewport, and the issue is gone now. 
![Screen Shot 2019-06-28 at 3 38 45 PM](https://user-images.githubusercontent.com/45409515/60366949-fda61e80-99ba-11e9-8a7b-a5a92630a829.png)
