### ISSUE TITLE
Simplify checkout flow

### ISSUE THREAD

**Issue by Bimde** [SAP/cloud-commerce-spartacus-storefront#1617] opened 2019-03-11 14:13 UTC
## Expected Results
Skip payment, address, and shipping steps when defaults are available. 

## Steps
- Address
  - `GET /users/{userId}/addresses`
  - If default address exists, call `PUT /users/{userId}/carts/{cartId}/addresses/delivery` to set the address for the cart and move to next step
  - Otherwise, show `Shipping Address` step from regular checkout
- Delivery mode (standard, express, etc.)
  - `GET /users/{userId}/carts/{cartId}/deliverymodes` to get available delivery options
  - `PUT /users/{userId}/carts/{cartId}/deliverymode` to select delivery mode (configurable by storeowner—see note in considerations section below)
- Payment method
  - `GET /users/{userId}/paymentdetails`
  - If default payment method exists, call `PUT /users/{userId}/carts/{cartId}/paymentdetails` to set the payment method for the cart and move to next step
  - Otherwise, show `Payment` step from regular checkout
- Summary page
  - This is the same `Review` step from the current checkout flow

**Comment by Bimde** [comment] 2019-03-12 20:09
Also add addition links to change payment / address / shipping speed details form the review page. More details here: https://wiki.hybris.com/display/spar/Quick+Buy+It+Button

**Comment by Xymmer** [comment] 2019-04-25 21:34
would love to get this in for 1.0 but can be after
we have to make sure it's clear you can click links to change info

**Comment by Xymmer** [comment] 2019-07-31 17:40
dupe of #88 which we're starting to work on

**Closed by Xymmer** 2019-07-31 17:40 UTC
Labels: closed/duplicate, express-checkout, type/improvement
