### ISSUE TITLE
Clicking on the upper header produces duplicate line

### ISSUE THREAD

**Issue by vekterdude** [SAP/cloud-commerce-spartacus-storefront#2241] opened 2019-04-30 17:59 UTC
Description:  Clicking on any of the upper header items will produce a second ‘line’ exactly like the rule (line) that divides the upper header from the header. This occurs mostly after page refresh, but stops after 2 or 3 upper header clicks

How to duplicate: Refresh homepage and click on any of the upper header items to see extra line appear.

Photos: (Too hard to screenshot)

**Comment by tobi-or-not-tobi** [comment] 2019-05-10 21:06
Cannot reproduce on latest environment. Can you double check.

**Comment by Xymmer** [comment] 2019-05-31 21:20
closing as can't repro, will bring it back if seen again. I haven't seen in for awhile

**Closed by Xymmer** 2019-05-31 21:20 UTC
Labels: type/bug
