### ISSUE TITLE
Fix failing E2E tests

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3550] opened 2019-07-03 14:36 UTC
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests

**Comment by RadhepS** [comment] 2019-07-09 18:04
Closing - the only test that is failing is regression/reset-password/forgot-password.e2e-spec.ts. This is because the dev17 backend is out of the date.

**Closed by RadhepS** 2019-07-09 18:04 UTC
Labels: e2e-tests
