### ISSUE TITLE
Can not customize cart detail page

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#3207] opened 2019-06-15 14:01 UTC
Like other some other component, I would like to customize cart detail page but its not working

## Steps to Reproduce
in B2cStorefrontModule I am using  following but StandardCmsComponentConfig do not have exported CartDetailsComponent
```
cmsComponents: {
        CartDetailsComponent: {
          component: CustomComponent
        }
```
Using: Spartacus Beta version:
  "@spartacus/core": "~0.1.0-beta.0",
    "@spartacus/styles": "~0.1.0-beta.0",
    "@spartacus/storefront": "~0.1.0-beta.0",
    "@spartacus/assets": "~0.1.0-beta.3"

**Comment by Platonn** [comment] 2019-06-18 11:29
The angular component is called `CartDetailsComponent`, but the CMS component name is `CartComponent`. So please configure:

```typescript
ConfigModule.withConfig(<CmsConfig>{
      cmsComponents: {
        CartComponent: {
          component: CustomComponent,
        },
      },
    }),
```

See default config: https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/feature/GH-2981/projects/storefrontlib/src/cms-components/cart/cart-details/cart-details.module.ts#L23-L25

**Comment by Xymmer** [comment] 2019-06-18 13:12
closing as not a bug, let us know if the solution doesn't work

**Closed by Xymmer** 2019-06-18 13:12 UTC
Labels: type/bug
