### ISSUE TITLE
[Retest DUPE - Dependent on GH-2877 once merged] iphone8+: Review stars are wrong

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3048] opened 2019-06-11 18:55 UTC
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Go to a pdp of a product without reviews, for eg: 2054947 

**Actual Result**
Some of the stars are in red.
![iphoneReviews](https://user-images.githubusercontent.com/45409515/59298371-6883f580-8c58-11e9-8464-1f8a19a1f8e2.jpeg)

For a product with reviews, eg 1981415, look at the 3rd star, it's missing a bit of red:
![iphoneReviews](https://user-images.githubusercontent.com/45409515/59298607-e47e3d80-8c58-11e9-8e2b-7056c2333fbf.jpeg)

Go to the reviews section and look at the stars:
![iphoneReviewStars](https://user-images.githubusercontent.com/45409515/59298767-2f985080-8c59-11e9-9293-b39ba3481cd2.jpeg)

**Comment by Xymmer** [comment] 2019-06-11 23:12
pretty sure i saw a similar ticket somewhere but couldn't find it.

**Comment by developpeurweb** [comment] 2019-06-13 17:59
This seems like a dupe of GH-2877 but in mobile, being the same affected area I'll sync them up as duplicates

**Comment by developpeurweb** [comment] 2019-06-18 14:58
please retest once GH-2877 is merged and deployed to model-t

**Closed by developpeurweb** 2019-06-18 14:58 UTC
Labels: type/bug

**Comment by KateChuen** [comment] 2019-06-19 14:26
Tested on dev17 using iphone8+:
![IMG_8481](https://user-images.githubusercontent.com/45409515/59773497-b661b480-927b-11e9-94dc-1106ef13180e.PNG)
![IMG_8480](https://user-images.githubusercontent.com/45409515/59773498-b661b480-927b-11e9-9698-688276f6333b.PNG)
![IMG_8479](https://user-images.githubusercontent.com/45409515/59773499-b661b480-927b-11e9-8e1b-71338af86ac6.PNG)
