### ISSUE TITLE
Add something to cart, reload, lose cart

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#2981] opened 2019-06-09 23:32 UTC
Not signed in, add something to cart, reload, lose cart
Same when signed in
But if I sign out then back in, cart comes back.

**Comment by dunqan** [comment] 2019-06-10 05:41
The quick fix for this is doable using configuration:
```
      state: {
        storageSync: {
          keys: {
            'cart': StorageSyncType.SESSION_STORAGE
          }
        }
      }
```
which basically syncs cart with session storage (could also be local storage).

But to make it as an official solution, we have to check, if there are no drawback (like not refreshed or stale cart, especially when it will be set to local storage, etc). Storing only cart id (not the whole cart) might be one solution for this.

**Comment by marlass** [comment] 2019-06-11 10:22
Quick fix doesn't work correctly. Some race conditions error appear.
I would also go for keeping only cart id, but we need to change store structure, a bit to now have it as object key, but as a value.

I am working on creating working version.

**Comment by plabadie** [comment] 2019-06-13 21:19
Did a smoke test.  Works well with anonymous user.  It doesn't work for an authenticated user.

I get this:

<img width="1660" alt="Screen Shot 2019-06-13 at 5 16 48 PM" src="https://user-images.githubusercontent.com/7065346/59468130-52646980-8dff-11e9-8711-5be7b7580324.png">


To repro:

- Authenticate
- Add a product to cart
- From the add to cart modal, go to the cart page
- Refresh the page.

**Comment by marlass** [comment] 2019-06-18 11:48
Improvement ticket for handling details in cart: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3241
Unit test ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3242

**Comment by Platonn** [comment] 2019-06-24 14:26
- anonymous user vs. logged in user
- loading cart vs. merging cart just after 
### QA steps:
1. As an anonymous user add to cart and refresh (veryfy that cart is keeped)
2. Because big refactor was mede in Cart Service, please do regression tests regarding **cart** and **page refresh** for combinations of conditions:
- anonymous user / logged in user / just registered fresh user
- create cart (add to cart when cart doesn't exist) / add to exising cart / clear cart (by logout or checkout)
- change language / currency
- login (merge anonymous cart) / logout (drop cart)
- anything more you think is worth testing...

**Comment by giancorderoortiz** [comment] 2019-06-25 20:14
I don't see a fix yet for this issue. 
Using registered user, I add items to cart, go to cart page, reload page -> cart is empty. 🆖 
Logout and re-login -> cart has contents again. 
Anonymous user -> once page is reloaded, cart contents are gone.  🆖

**Comment by Xymmer** [comment] 2019-06-25 20:23
kate to retest, gil/radhep say it works, gc still not so, if it works, we'll pass

**Comment by KateChuen** [comment] 2019-06-25 20:30
Tested on dev17, chrome. I still see the issue too, empty cart after reloading.

**Comment by Xymmer** [comment] 2019-06-25 21:08
in summary, GC and Kate see the issue, Gil and Radhep don't.

**Comment by Xymmer** [comment] 2019-06-25 21:13
Adding to the mix:
- Chrome: Cleared cache and cookies, anonymous user, go to dev17, add to cart, show cart, reload, cart gone.
- Same with Firefox

**Comment by Xymmer** [comment] 2019-06-25 21:18
BUT!
Using modelt, Firefox, signed in, cart is saved on reload.
Same with Chrome, when signed in.

**Comment by Platonn** [comment] 2019-06-26 08:14
My bad, I tested only using dev version of spartacus (`yarn start`). The fix doesn't work in production build i.e. `yarn start --prod` (or `yarn build` which is used in our deploy script). I confirm that for production build cart is gone after page refresh - both for anonymous and signed in user. 

Note: for signed in user, the cart is back when you logout and login again - so cart is persisted on backend, but the refreshing the page causes the local (frontend) version of cart to disappear.

**Comment by marlass** [comment] 2019-06-26 14:36
Problem is about storageSync. 
`cartStoreConfigFactory` is not executed at all.

Quick fix for this problem: add cart `guid`, `code` keys in `auth-store.module.ts`. This is not an elegant solution.

A better approach would be fixing the storageSync config providing.

Removing config from `auth-store.module` doesn't help. Still, `cartStoreConfigFactory` isn't executed.

**Comment by bgambocjaviniar** [comment] 2019-06-26 15:02
Fix because StateModule was missing in cart-store.module.ts
Adding fix to a new PR

Fix in GH-3407

**Comment by RadhepS** [comment] 2019-06-26 15:52
Refresh issue is fixed but there is another bug that should be fixed before this feature is deployed.

1. Login
2. Add an item to the cart
3. Logout
4. Add an item to cart (as anon user)
5. Log back in to account and you will see an error message
6. You will also not be able to place an order with that cart

**Closed** 2019-06-26 17:31 UTC
Labels: priority/HIGH, type/bug

**Comment by giancorderoortiz** [comment] 2019-06-27 17:59
Test successful 🆗 
(But minicart flickers for about 1 second with qty = 0, then updates correctly).
