### ISSUE TITLE
Spinner When Missing Addons for Stock Notification

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5571] opened 2019-11-28 16:07 UTC
**Setup:**
1. frontend branch feature/notification-preferences_my-interests_stock-notification branch
2. backend deployed without necessary addons to support stock notification feature. (i.e. notificationoccaddon, customerinterestsoccaddon, stocknotificationservices)

**Steps to Reproduce:** 
1. Navigate to dev-com6 and sign-in (deployed with 
feature/notification-preferences_my-interests_stock-notification branch. )
1.a. http://dev-com-6.accdemo.b2c.ydev.hybris.com:4200/
2. Search for sku with no available stock. (i.e. 726511)
3. Navigate to PDP page of found sku with no available stock. 
3. Click on Notification Channels. 
4. On Notification preference page, enable a desired channel of communication. 

**Expected Results:** 
4. Either options to select/enable, or a message indicating feature is not available. 

**Actual Results:** 
4. Spinner shown. There is no info. No meaningful information passed to the user. 
4.a. API calls to notificationpreferences fail with 404

![Screen Shot 2019-11-28 at 10 53 19 AM](https://user-images.githubusercontent.com/46171897/69821014-7ad6f900-11d0-11ea-9464-d4a051cb5113.png)

**Comment by giancorderoortiz** [comment] 2019-11-28 16:07
Refers to #5123

**Comment by kate1zheng** [comment] 2019-12-02 08:59
same issue with https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5572

**Comment by Xymmer** [comment] 2019-12-11 19:19
as stock notification is cms based, you would add the cms (or remove it) based on if you want this feature, so closing as not a bug, as designed.

**Closed by Xymmer** 2019-12-11 19:19 UTC
Labels: bug, stock-notification
