### ISSUE TITLE
Header menus are left aligned

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#2913] opened 2019-06-05 16:56 UTC
possibly after removing ng-bootstrap and Bootstrap tags the menus got left aligned and got back to all uppercased type. @Xymmer requested type to be Capitalized since the very beginning of the project, Bill pls confirm if this is still the case.

**before**
![58816027-a9e02980-85f6-11e9-9d86-47509c644ebe](https://user-images.githubusercontent.com/15113219/58974617-c617ce00-8790-11e9-9816-9f49ee2e2689.png)

**after**
![Screen Shot 2019-06-05 at 12 50 55 PM](https://user-images.githubusercontent.com/15113219/58974630-ce700900-8790-11e9-8724-973611352c47.png)

**Comment by Xymmer** [comment] 2019-06-05 17:23
checking on this

**Comment by tobi-or-not-tobi** [comment] 2019-06-05 17:54
We've aligned the implementation with the designs from PD team, including uppercase and left alignment. I think it's fine and believe it's their domain, and it looks great, espcially on mobile from my perspective.

**Comment by Xymmer** [comment] 2019-06-05 17:57
so it's as intended, closing

**Closed** 2019-06-26 01:58 UTC
Labels: css
