### ISSUE TITLE
Carts created with Spartacus aren't found through regular postman calls

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront#3349] opened 2019-06-24 16:36 UTC
If I start a cart in Spartacus then log in later using postman, i don't see the cart

![image](https://user-images.githubusercontent.com/4998145/60036204-a92e3680-967c-11e9-811e-cf4995dfb48e.png)

![image](https://user-images.githubusercontent.com/4998145/60036165-9156b280-967c-11e9-849d-d971aa7bc87d.png)

by design?

**Comment by Xymmer** [comment] 2019-06-24 17:07
Not saying this is a bug perse but why can't we see them in postman?

**Comment by WeizhengSap** [comment] 2019-07-18 15:13
Maybe related to this one: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3684

**Comment by KateChuen** [comment] 2019-07-18 18:55
Wasn't able to reproduce. Was able to retrieve the cart using postman
https://electronics.dev-com-17.accdemo.b2c.ydev.hybris.com:9002/rest/v2/electronics-spa/users/kate.dev17@acme.com/carts/00000424

<img width="1090" alt="Screen Shot 2019-07-18 at 2 54 29 PM" src="https://user-images.githubusercontent.com/45409515/61484050-08c1ee00-a96c-11e9-803a-eafdbb8a35a3.png">

**Comment by WeizhengSap** [comment] 2019-07-18 19:22
I will close this ticket because it works on my local as well.

**Closed by WeizhengSap** 2019-07-18 19:22 UTC
Labels: cart-page
