### ISSUE TITLE
Should not be able to add "base" product to cart

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#3044] opened 2019-06-11 17:57 UTC
## Environment Details

- Spartacus:  
- Browser: 
- OS: 
- Device: 
**Mac/Safari** 
- Other environment details: 

## Steps to Reproduce
1. Open category "Compact Cameras", and click product "PowerShot A480"
![Screen Shot 2019-06-11 at 1 48 43 PM](https://user-images.githubusercontent.com/44440575/59294856-69188e00-8c50-11e9-98e9-3b6c2dfd0a6d.png)

2. In "You may also like...", click the first product

3. try to add this product to cart; the "add to cart" popup overrides the error message
![Screen Shot 2019-06-11 at 1 55 52 PM](https://user-images.githubusercontent.com/44440575/59295013-ae3cc000-8c50-11e9-87c0-e32057990f4c.png)

4. close the popup, we can see this:
![Screen Shot 2019-06-11 at 1 29 31 PM](https://user-images.githubusercontent.com/44440575/59294894-80577b80-8c50-11e9-8a49-5624d48a3725.png)

This product is a "base" product

**Comment by Xymmer** [comment] 2019-06-11 23:08
we don't support multi-dimensional products in first release

**Comment by mirkosoft** [comment] 2019-10-03 10:33
It might be related to #4821

**Comment by psmul** [comment] 2019-10-16 12:13
Couldn't reproduce the problem. 
There are two types of "ngIf" conditionals controlling visibility of "Add to cart" button.
1. PLP - for list view there is single information to check - `stockLevelStatus`. There is no check for stock number nor this information is coming from backend.
2. PDP - gets more detailed checks with stockLevelStatus and stock number available. Although for PDP we get stock number which is absent for most PLP products.

This causes an error, because backend sends incomplete information for PLP items.

**Comment by psmul** [comment] 2019-10-17 11:04
After more investigating the issue, I believe the current problem lies in the backend side:
For endpoint: **/products** with parameters **fields=products** and **stock(FULL)** response with list of products **not always** contains field **stockLevel**, which should be always returned, even when value is 0.

**Comment by tobi-or-not-tobi** [comment] 2019-10-29 08:28
Generally speaking, a base product cannot be ordered and should therefor not have any stock assigned to it. There is however some parts in the sample data where stock has been added for base products. We should fix the sample data in this case.

**Comment by Matejk00** [comment] 2020-01-13 10:24
Sample data PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/60

**Comment by mirkosoft** [comment] 2020-01-22 09:56
QA: since spartacus sampledataaddon is fixed so that products doesn't have stock anymore, issue is gone, ie. there is no such product anymore in "You may also like..." section.

**Closed** 2020-01-24 09:16 UTC
Labels: P3, bug, multi-dimensional-products, sample-data
