### ISSUE TITLE
In PDP, product image is not updated after clicking another product in "You may also like..."

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/cloud-commerce-spartacus-storefront#3041] opened 2019-06-11 17:24 UTC
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  
- Browser: 
- OS: 
- Device: 
**Mac/Safari** 
- Other environment details: 

## Steps to Reproduce
Open PDP page, click one product in the "You may also like...". Sometimes, the main product image is still the old one. It does not happen all the time. 

![Screen Shot 2019-06-11 at 1 19 33 PM](https://user-images.githubusercontent.com/44440575/59292997-3a001d80-8c4c-11e9-9e0c-b6bd8f1d026a.png)

**Comment by mirkosoft** [comment] 2019-06-17 09:23
Can't reproduce it. @WeizhengSap can you confirm is this still an issue and if yes pls provide env details.

**Comment by mirkosoft** [comment] 2019-06-18 11:14
closing as not happening anymore @WeizhengSap

**Closed by mirkosoft** 2019-06-18 11:14 UTC
Labels: type/bug
