### ISSUE TITLE
E2E tests: mobile-checkout test is not stable

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3670] opened 2019-07-15 14:35 UTC
the checkout-flow-mobile.e2e.spec.ts test has been failing once every week now. 
Can we take a look and see if we can make it more stable?

**Comment by LTiger14** [comment] 2019-07-17 19:10
Could not reproduce locally. I can see it fail on travis so I know there is a problem. Maybe someone will have better luck :S

**Comment by RadhepS** [comment] 2019-07-18 18:17
Can't repro locally either.

Perhaps we can wait and see if this ticket potentially fixed it: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3586

**Comment by plabadie** [comment] 2019-07-23 14:58
Can't repro locally or using dev 17.  Looked back the 5 last days and the test is also stable on Jenkins.

Closing the ticket.  Let's open a new one if/when the issue comes back and we have more to work with for figuring out what can be going wrong.

**Closed by plabadie** 2019-07-23 14:58 UTC
Labels: e2e-tests
