### ISSUE TITLE
coupons e2e tests failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6148] opened 2020-01-20 04:22 UTC
Coupons e2e test are now failing again

Files:
- projects/storefrontapp-e2e-cypress/cypress/integration/regression/coupon/coupon.e2e-spec.ts
- projects/storefrontapp-e2e-cypress/cypress/integration/mobile/coupon/coupon.e2e-spec.ts

Coupon codes couponCode1, couponCode2 and couponCode3 are not defined

<img width="1078" alt="Screen Shot 2020-02-10 at 1 58 11 PM" src="https://user-images.githubusercontent.com/30666844/74180387-6621d300-4c0d-11ea-9500-31b572bc7f98.png">

**Comment by psmul** [comment] 2020-01-23 12:48
It looks like backend problem, not returning lowered price for the product with a discount via coupon, nor the coupon itself is returned in cart view.

**Comment by psmul** [comment] 2020-01-28 14:02
Sampledata also merged here:
https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/63

**Comment by psmul** [comment] 2020-02-04 09:16
QA steps:
- launch e2e tests for coupons 

Expected result:
- tests should pass

**Comment by mirkosoft** [comment] 2020-02-05 11:19
Below spec has been run and passed:
`regression/coupon/coupon.e2e-spec.ts`
`mobile/coupon/coupon.e2e-spec.ts`

**Comment by psmul** [comment] 2020-02-11 10:16
QA steps:
- simply run coupon `coupon.e2e-spec.ts` both for mobile and regression against dev-12

Expected result:
- tests should pass

**Comment by Matejk00** [comment] 2020-02-11 10:30
QA done, tests are passing.

**Comment by hackergil** [comment] 2020-02-17 15:52
Failing in 1.5.x branch

**Comment by hackergil** [comment] 2020-02-17 17:01
There were changes in developed that were not present on the 1.5.x branch. Tests should pass now

**Comment by plabadie** [comment] 2020-02-19 18:56
Fails on 1.5.x
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/20/consoleText

**Comment by qjimmy** [comment] 2020-02-20 21:08
PR #6656

**Comment by qjimmy** [comment] 2020-02-21 17:06
On hold, failing due to cart error. Wait until Marcin's cart fix in 2.0

**Comment by qjimmy** [comment] 2020-03-04 18:39
PR #6782

**Closed** 2020-03-10 07:50 UTC
Labels: 1.5-e2e, e2e-tests
