### ISSUE TITLE
Delay for the menu styles to kick-in makes menu display in wrong position

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#2014] opened 2019-04-12 22:25 UTC
Seems there's a delay for the styles to kick-in, when a page loads for the first time, the menus are misplaced as per screenshot, but once you click on them for the second time the issue goes away. 

This wasn't a problem before but it started happening around April 10th, not sure if it's a delay on the styles or on the server.

![Screen Shot 2019-04-11 at 4 26 43 PM](https://user-images.githubusercontent.com/15113219/55991014-3ca7bc00-5c77-11e9-85dd-e5e771ee332b.png)

![Screen Shot 2019-04-11 at 4 24 48 PM](https://user-images.githubusercontent.com/15113219/55991031-44676080-5c77-11e9-9019-c7c4b9a883b7.png)

**Comment by KateChuen** [comment] 2019-04-18 13:35
To retest. Might be fixed now.

**Comment by developpeurweb** [comment] 2019-05-06 19:17
@KateChuen  I still see this bug on `develop` as of today, could it be a server delay issue?
I'm testing with `dev-com-17`
I'm sending this back to To Do, although I'm not sure this has anything to do with styling,  @Xymmer can we try other team boards to so if other devs may have the answer

**Comment by hackergil** [comment] 2019-05-09 16:40
This is being caused by a bug introduced in ng-bootstrap 4.1.1. Locking up the version until it is fixed. Also we have to consider that we won't use bootstrap for long.

**Comment by KateChuen** [comment] 2019-05-13 14:30
Still able to reproduce this issue on dev17. 

- Click on the drop down arrow next to Brands 
- Click on the drop down arrow next to Digital Camera
- Login or Register a new user
- Click on the drop down arrow next to Brands again

![Screen Shot 2019-05-13 at 10 18 10 AM](https://user-images.githubusercontent.com/45409515/57629436-cb0aa880-7569-11e9-9d03-0e273039552e.png)

**Closed** 2019-05-13 16:32 UTC
Labels: type/bug, ux

**Comment by KateChuen** [comment] 2019-05-14 14:53
Tested on dev17. Looks good now.
