### ISSUE TITLE
[Product Grid View] Product name goes behind rating/price when it is very long 

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3776] opened 2019-07-25 18:35 UTC
## Environment Details

Chrome/Mac

## Steps to Reproduce
I went to the product grid view page. I targeted a specific product and changed it's product-name value using the console on Chrome. I made the value very long.

Expected result: 
Product-name area expands and the content below it shift downwards.

Observed result:
The content below it does not shift causing the text to be behind the rating/price.
![Screen Shot 2019-07-25 at 2 32 49 PM](https://user-images.githubusercontent.com/34665674/61899280-1f76c080-aee9-11e9-92e1-9b1ec8cc01da.png)

**Comment by KateChuen** [comment] 2019-10-11 18:53
Tested on dev10. It looks ok on desktop view. 

But not on mobile. Go to "Digital Cameras -> Shop all digital cameras -> 4th page or directly to this page (: https://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/Open-Catalogue/Cameras/Digital-Cameras/c/575?currentPage=3


Although the name is not displayed on top of the review stars anymore, there's still an issue with the alignment. On the list view on mobile: You get this:
![Screen Shot 2019-10-11 at 2 47 26 PM](https://user-images.githubusercontent.com/45409515/66676809-55008f80-ec36-11e9-96dd-e5c26105de27.png)


If you go grid view on mobile: You get this, looks like the left side is truncated.
![Screen Shot 2019-10-11 at 2 47 11 PM](https://user-images.githubusercontent.com/45409515/66676824-5cc03400-ec36-11e9-9b1b-8359b0ebc6ec.png)

Re-opening this ticket.

**Comment by mikelMHybris** [comment] 2019-10-17 14:13
The problem is coming from the pagination. It looks like when too many page numbers are shown in the mobile view the page width takes the width of the pagination. In the mobile view can we limit the number of pages are in the pagination? Like "<|1|2|...|18|>". It seems like that is the maximum amount of pages we can use with out it breaking the page at the smallest view port.

**Comment by KateChuen** [comment] 2019-11-07 19:48
It's fixed, as in, the name isn't truncated anymore. But there's still a spacing issue. 

Spacing is ok on pages 1-3.
![Screen Shot 2019-11-07 at 2 46 33 PM](https://user-images.githubusercontent.com/45409515/68422158-a0428b00-016d-11ea-8574-e306187d5a90.png)
But then on page 4 and onwards, there's no spacing.

![Screen Shot 2019-11-07 at 2 46 12 PM](https://user-images.githubusercontent.com/45409515/68422149-9d479a80-016d-11ea-87a7-782161789124.png)

**Comment by mikelMHybris** [comment] 2019-11-15 15:54
@KateChuen we will have to fix the pagination issue in a separate ticket.

**Comment by KateChuen** [comment] 2019-11-20 14:29
Closing this ticket. 
Created ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5487 for the pagination issue.

**Closed by KateChuen** 2019-11-20 14:29 UTC
Labels: P3, bug, theme-calydon
