### ISSUE TITLE
Regression test May 8 2019 lib release

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2324] opened 2019-05-07 12:53 UTC
- [x] Run all the E2E tests on the nightly branch on jenkins:
Note: Make sure that ALL the tests are being run (about 29 tests).
OR run them from your computer, pointing to dev17 server.

Additionally, do a quick smoke test (equivalent to the big happy path test) on:
- [x] Safari
- [x] Firefox

**Comment by marlass** [comment] 2019-05-09 16:20
Two new regressions found with e2e tests.

- In product details page in the shipping tab "Lorem ipsum" is missing.
- If you try to register using same email and password instead of error message now you will be logged in. If you use another password you get "Bad login credentials"

@Xymmer Are you aware of these changes? Is it intended behavior or this needs to be fixed?

**Comment by KateChuen** [comment] 2019-05-09 17:30
@marlass : 
for the pdp issue: it keeps coming back. We had a ticket(https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/1745) for it, and it was supposedly fixed. but i guess it's back again. 

for the register user: behavior as designed (they changed the behavior in the backend recently to match this. For security reason, they just let the existing user logs in if he tries to register again).

**Comment by marlass** [comment] 2019-05-13 12:20
PDP issue reopened. Registry behavior is documentation process.
Closing this issue.

**Closed by marlass** 2019-05-13 12:20 UTC
Labels: z/releasing
