### ISSUE TITLE
Page is not refreshing in SmartEdit

### ISSUE THREAD

**Issue by RobertOzgaSap** [SAP/cloud-commerce-spartacus-storefront#1812] opened 2019-03-26 14:12 UTC
Many of smartedit operations require component to be refreshed after execution, like:
- move component 
- edit component
- add new component
- remove component
in personalization
- add action
- edit action
- remove action

Are not working properly because components/page is not refreshed. Forcing page to reload shows that actions were properly executed by backend but frontend did not refresh.

Console shows `prelibraries.js:142 renderService: parentOverlay empty for component:` (for multiple different components).

Actions that forces whole page to be refreshed are working (e.g. select target group in personalization).

**Comment by WeizhengSap** [comment] 2019-04-01 12:46
I cannot reproduce it on my local. It may be caused by this ticket https://jira.hybris.com/browse/CMSX-8520. So, I will close this ticket.

**Closed** 2019-04-10 17:49 UTC
Labels: z/personalization, z/smartedit
