### ISSUE TITLE
[Desktop/Edge] - On Forgot Password Reset, Autocomplete gets stuck

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3502] opened 2019-07-02 09:27 UTC
When signing in and going to forgot password on desktop edge browser, make sure you have a previous address that the email address box suggests. Put in any email address and Submit. The autocomplete box is opened on the next page and stays on the screen until another autocomplete box is opened (even through page transition).

![image](https://user-images.githubusercontent.com/11735817/60501250-026d1a00-9cbc-11e9-95c3-d3d68e98b821.png)

**Comment by psmul** [comment] 2019-07-15 13:44
Due to inability to reproducing bug by few dev, we're closing it for now. To be re-opened in case if error shows up.

**Closed by psmul** 2019-07-15 13:44 UTC
Labels: priority/LOW, type/bug, ux
