### ISSUE TITLE
Console 404 on Logout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#4734] opened 2019-09-25 13:30 UTC
**Steps to Reproduce:** 
~1. Enable guest checkout and express checkout features.~
2. Navigate to storefront and login. 
~3. Add products to cart and place order.~
4. Sign out. 

**Expected Results:** 
4. No errors in dev console. 

**Actual Results:** 
4. Call to GET 9002/rest/v2/electronics-spa/cms/pages?fields=DEFAULT&pageType=ContentPage&pageLabelOrId=/logout&lang=en&curr=USD returns with 404. 
4.a. Response message" : "No content page found matching the provided label or id: /logout"

**Images:** 

![Screen Shot 2019-09-25 at 9 18 20 AM](https://user-images.githubusercontent.com/46171897/65605275-d1c51580-df76-11e9-8a32-b32d0072aca1.png)
![Screen Shot 2019-09-25 at 9 18 33 AM](https://user-images.githubusercontent.com/46171897/65605276-d1c51580-df76-11e9-9ab0-8753cb83a887.png)

**Comment by Pucek9** [comment] 2019-10-01 09:44
@giancorderoortiz 
The issue is not related to `express checkout` and/or `guest checkout`. It occurs also when they are turned off (and sign out on every page).

**Comment by Pucek9** [comment] 2019-10-01 09:53
It's a duplicate of #2460. As @tobi-or-not-tobi suggest behavior is correct

**Closed by Pucek9** 2019-10-01 09:53 UTC
Labels: STILL NEEDED?, type/bug
