### ISSUE TITLE
skip links is causing an console error when moving to and from SLR cameras (not related to skipping)

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#6086] opened 2020-01-15 06:50 UTC
## Environment Details

- Spartacus:  develop branch
- Browser: Chrome
- OS: macOs Catalina
- Device: MBP

## Steps to Reproduce
1. open chrome dev tools
2. open webcams category page
3. open SLR cameras category page
4. open camcorders category page

## Observed Results
On step 3 and 4, the `ExpressionChangedAfterItHasBeenCheckedError` is thrown. 

## Expected Results
The `ExpressionChangedAfterItHasBeenCheckedError` should not be thrown. 

## Additional Information
Most likely the fact that the SLR cameras category has an alternative page template without the slots `ProductLeftRefinements` and `ProductListSlot` is related.

**Comment by Zeyber** [comment] 2020-01-15 08:09
I've seen that error before when the DOM is changed twice seemingly simultaneously by some dynamic element. It could be by something pushing elemments twice to the skip links behaviour subject (on route change perhaps?). In my experience, this doesn't break anything. It just leaves an ugly error in your console.

**Comment by Xymmer** [comment] 2020-01-15 18:38
@Zeyber is there anything we can do about it, or should we just close it? is it frequently seen?

**Comment by Zeyber** [comment] 2020-01-16 10:54
We can and should fix it, but it only affects those looking at the dev console.

**Comment by dunqan** [comment] 2020-01-16 12:09
I can confirm I was able to reproduce it also on a home page while resizing the window from desktop to mobile width.

**Comment by giancorderoortiz** [comment] 2020-01-18 01:29
Unable to reproduce with MacOS Mojave 10.14.6

**Comment by Platonn** [comment] 2020-01-21 11:13
Skip links is a part of 1.5 version (so it's now in branch `develop`). But similar error occurs in the branch `release/1.4.x` with BreadcrumbComponent: see https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6192. I suggested there a solution to both problems (this ticket and 6192).

**Closed** 2020-01-27 13:30 UTC
Labels: P2, bug

**Comment by marlass** [comment] 2020-02-11 07:16
Tested and I no longer see the error in console.
