### ISSUE TITLE
[Mobile] Product tabs should be collapsable

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#3513] opened 2019-07-02 10:52 UTC
Clicking `-` should collapse product tabs but instead does nothing.

![image](https://user-images.githubusercontent.com/11735817/60507302-23d40300-9cc8-11e9-9e19-0d76627a61cf.png)

**Comment by Xymmer** [comment] 2019-07-03 22:45
dupe of #3053

**Closed by Xymmer** 2019-07-03 22:45 UTC
Labels: type/bug, ux
