### ISSUE TITLE
Cart looks squished on mobile header

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#3068] opened 2019-06-11 20:27 UTC
(also see #3144)

- On mobile view -> Header -> wide black bar, but then the cart looks squished. 
<img width="657" alt="smallCartIcon" src="https://user-images.githubusercontent.com/45409515/58821438-0e08ea80-8603-11e9-859f-20979a640201.png">

Originally part of GH-2835
cc @KateChuen

**Comment by Xymmer** [comment] 2019-06-21 15:51
since we have the room, it should stay the same in all viewports right?
![image](https://user-images.githubusercontent.com/4998145/59935071-f4e1a580-941a-11e9-9f31-54baf74324e0.png)

**Comment by developpeurweb** [comment] 2019-06-25 16:34
This is not a bug, that seems like the browser's top separation line blending with the design, if i set the background to a lighter color, the separation line becomes more evident.

![Screen Shot 2019-06-25 at 12 27 22 PM](https://user-images.githubusercontent.com/15113219/60115892-f07ffa00-9744-11e9-8308-47075148a0f3.png)

@Xymmer in response to the previous question, the current state is as per mockups (see below).
Are you suggesting we change this to look like the screenshot you provide? Please clarify.

![Screen Shot 2019-06-25 at 12 28 00 PM](https://user-images.githubusercontent.com/15113219/60116112-697f5180-9745-11e9-9153-d6ba04ea07eb.png)

**Comment by Xymmer** [comment] 2019-06-25 16:41
ok so not a bug, and if that was the design, let's leave as is
closing

**Closed by Xymmer** 2019-06-25 16:41 UTC
Labels: css, type/improvement
