### ISSUE TITLE
Remove button on cart has a grey background when in mobile view

### ISSUE THREAD

**Issue by RadhepS** [SAP/cloud-commerce-spartacus-storefront#3455] opened 2019-06-28 15:24 UTC
![Screen Shot 2019-06-28 at 11 23 53 AM](https://user-images.githubusercontent.com/34665674/60353108-4cda5800-9997-11e9-9f8b-23752c814695.png)

**Comment by developpeurweb** [comment] 2019-07-10 18:07
Unable to reproduce or no longer an issue.
If still an issue please provide more detail: server, browser, device, orientation.

**Comment by KateChuen** [comment] 2019-07-15 15:43
It's actually visible on mac/safari and I also saw it on windows/firefox (https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3043)
Add a product to cart, then Go to cart page, for eg: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/cart

**Comment by developpeurweb** [comment] 2019-07-18 19:21
This is getting fixed in GH-3598 as a test case

**Comment by KateChuen** [comment] 2019-09-18 17:54
Tested with calydon enabled, on safari, chrome and firefox, desktop and mobile viewports.
Remove button no longer has a grey background.

<img width="923" alt="Screen Shot 2019-09-18 at 1 54 02 PM" src="https://user-images.githubusercontent.com/45409515/65172900-cbd1b080-da1b-11e9-9b8b-cf2fc1144e54.png">

**Closed by KateChuen** 2019-09-18 17:54 UTC
Labels: styling, theme-calydon, type/bug
