### ISSUE TITLE
[done with 5154] Coupons Used Not Shown in Order Details Page

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5185] opened 2019-10-28 13:46 UTC
**Setup:** 
1. in Backoffice, enable and publish promotion rule "coupon_code_fixed_discount".
1.a. Make sure coupon SUMMER69's validity and redemptions are greater than 0, and not already used. 

**Steps to Reproduce:** 
1. Navigate to Spartacus storefront. 
2. Add items to cart. 
3. In cart page, add coupon "SUMMER69". 
4. Proceed to checkout. 
5. After order is placed, navigate to order details page. 

**Expected Results:** 
5. Coupon "SUMMER69" is listed as having been used. 

**Actual Results:** 
5. No coupon is listed. Only the discount is available (which is inferred to come from the coupon).

**Comment by giancorderoortiz** [comment] 2019-10-28 13:57
Old-Accelerator:
![Screen Shot 2019-10-28 at 9 46 38 AM](https://user-images.githubusercontent.com/46171897/67684311-4cfc5b80-f969-11e9-8bac-91dc6a098062.png)

**Comment by giancorderoortiz** [comment] 2019-10-28 13:57
Spartacus: 

![Screen Shot 2019-10-28 at 9 57 33 AM](https://user-images.githubusercontent.com/46171897/67684366-67ced000-f969-11e9-9287-6347a05ec140.png)

**Comment by Xymmer** [comment] 2019-10-28 21:00
Dupe of #5154

**Closed by Xymmer** 2019-10-28 21:00 UTC
Labels: coupons, type/bug
