### ISSUE TITLE
Checkboxes in filters doesn't look good on mobile

### ISSUE THREAD

**Issue by marlass** [SAP/cloud-commerce-spartacus-storefront#3495] opened 2019-07-02 06:24 UTC
Filters on mobile view have overlapping text with checkboxes.

![storefrontapp marlas now sh_(iPhone X)](https://user-images.githubusercontent.com/6259079/60488621-b366bb00-9ca2-11e9-934b-b53c89649370.png)

**Comment by Pucek9** [comment] 2019-07-02 09:37
Duplicate of #3057

**Closed** 2019-07-02 09:37 UTC
Labels: styling, type/bug
