### ISSUE TITLE
Add coupon impex to apparel store.

### ISSUE THREAD

**Issue by mazamcodes** [SAP/cloud-commerce-spartacus-storefront#5145] opened 2019-10-23 20:34 UTC
Linked from:

https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5031

Add coupon impex to apparel store since it had not been merged at time and coupons were only added to powertools store so far.

**Comment by LTiger14** [comment] 2020-01-28 15:29
Duplicate of #6283

**Closed by LTiger14** 2020-01-28 15:29 UTC
Labels: apparel-sample-data, coupons
