### ISSUE TITLE
Cart not found error won't go away after hotfix is applied

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#3555] opened 2019-07-03 17:48 UTC
**Environment Details**
Spartacus: Release 1.0 + hotfix
Browser: Chrome
Device: mac
Happens on: http://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
Login and add an item to cart before the hotfix.
Apply the hotfix. 
Go back to spartacus storefront.
Sign out.
Reload the homepage

**Actual Result**
The "cart not found" error is displayed. But even after closing it, it comes back right away. The only way to get rid of it is to login again.

![Screen Shot 2019-07-03 at 1 43 33 PM](https://user-images.githubusercontent.com/45409515/60613575-29e5e480-9d99-11e9-8fa7-47cbbc9d4dac.png)

**Comment by Xymmer** [comment] 2019-07-04 13:16
haven't been able to repro, we'll keep an eye

**Comment by marlass** [comment] 2019-07-08 08:22
Duplicate of #3478

**Closed by marlass** 2019-07-08 08:22 UTC
Labels: type/bug
