### ISSUE TITLE
Smartedit still using standard BaseSiteService

### ISSUE THREAD

**Issue by mrSingh007** [SAP/cloud-commerce-spartacus-storefront#4715] opened 2019-09-24 12:43 UTC
hi,

I have wrote my own baseSiteService and in `app module` changed provider as:
```
{
      provide:BaseSiteService,
      useClass:MyBaseSiteService
    }
```
Its working for storefront without any problem but on smartedit its giving problem as Smartedit still using standard BaseSiteService even I have provided here my own.

 ## Environment Details

- angular  version : "~8.2.0",
- spartacus version:  "~1.1.1"
- Platform : Linux (Centos OS7)

## Steps to Reproduce

Write own state and own BaseSiteService now define your custom `getBaseSiteData` method.
You will see for smartedit its not taking your method

## Offer to Fix
NO

**Comment by WeizhengSap** [comment] 2019-09-25 13:23
I tested this on my local by creating a `CustomBaseSiteService`:
```
import { Injectable } from '@angular/core';
import { BaseSiteService, BaseSite } from '@spartacus/core';
import { Observable } from 'rxjs';

@Injectable()
export class CustomBaseSiteService extends BaseSiteService {
  /**
   * Get the base site details data
   */
  getBaseSiteData(): Observable<BaseSite> {
    console.log('custom base site');
    return null;
  }
}
```
And, in `app.module`, I add this:
```
providers: [
    {
      provide: BaseSiteService,
      useClass: CustomBaseSiteService,
    },
  ],
```.
Open smartedit, I can see that the `CustomBaseSiteService` is used.
![Screen Shot 2019-09-25 at 9 23 05 AM](https://user-images.githubusercontent.com/44440575/65604857-24520200-df76-11e9-8dbe-4d11e6130b1b.png)

**Comment by WeizhengSap** [comment] 2019-09-25 15:38
I also tested it in prod build. It can't reproduce.

**Comment by Xymmer** [comment] 2019-09-29 21:28
closing as can't repro / works as designed

**Closed by Xymmer** 2019-09-29 21:28 UTC
Labels: type/bug
