### ISSUE TITLE
Submit review does not provide user feedback for submission result

### ISSUE THREAD

**Issue by Zeyber** [SAP/cloud-commerce-spartacus-storefront#4964] opened 2019-10-11 10:57 UTC
After writing a review and clicking submit, the form is reset and closed and a submission request sent whether the data is valid or invalid. The server response should provide the user with feedback as to whether they need to edit the form to make a valid request or have the form closed and reset after the submission is succussful.

**Comment by KateChuen** [comment] 2019-10-16 18:07
duplicate of #

**Comment by kacperknapik** [comment] 2019-12-09 11:53
NOTE: work on products' reviews submitions in general - errors, global messages' translations, etc

**Comment by kacperknapik** [comment] 2019-12-30 10:59
Will have to split the work into smaller tickets. Parking this ticket for now.

**Comment by kacperknapik** [comment] 2020-02-28 13:49
This will be closed in #6742

**Closed by kacperknapik** 2020-02-28 13:49 UTC
Labels: a11y/accessibility :wheelchair:, a11y/bug
