### ISSUE TITLE
Can't got through the search list with my keyboard arrow keys (up/down)

### ISSUE THREAD

**Issue by zebercut** [SAP/cloud-commerce-spartacus-storefront#3058] opened 2019-06-11 19:37 UTC
## Environment Details
- Spartacus:  Beta
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/
- Browser: 
- OS: 
- Device: 

## Steps to Reproduce
1. Login to Spartacus
2. Search for an item
3. The search result shows in a list
4. I can't move through the items with my arrow keys

## Additional Information

![image](https://user-images.githubusercontent.com/6307948/59301111-d6cbb680-8c5e-11e9-9ac4-ffb0e94dc292.png)

**Comment by Xymmer** [comment] 2019-06-11 22:32
dupe of #3028, in progress

**Closed by Xymmer** 2019-06-11 22:32 UTC
Labels: type/bug
