### ISSUE TITLE
Safari: Missing Visual Focus on Update Password Form

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront#4314] opened 2019-08-29 18:11 UTC
![Screen Shot 2019-08-29 at 2 09 07 PM](https://user-images.githubusercontent.com/15113219/63965287-cc070d80-ca66-11e9-8bfb-ec94cf888bb7.png)

missing focus on input fields and buttons

**Comment by Zeyber** [comment] 2019-10-15 07:26
Focus is visible on forms. Hard to see on buttons on chrome.

**Comment by KateChuen** [comment] 2020-01-07 15:59
Closing as duplicate of #4334

**Closed by KateChuen** 2020-01-07 15:59 UTC
Labels: a11y/ux :art:, a11y/ux/focus, theme-calydon
