### ISSUE TITLE
Performance improvements for Product load

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3666] opened 2019-07-13 15:28 UTC
The product detail payload is currently huge, and used in multiple places. For example in the product carousel we only use the name, price and primary image, but the FULL data set is loaded. Ideally we break up the product load into pieces, so we can gradually load data. 
- small data set that provides product basics to load product data in a carousel as well as build the fundamental page layout of the PDP
- load the rich data set. 
- consider loading product features in a sub-sequential call as it's loaded below the fold (or in a tab). 

There is also product data that should be loaded more frequently and cannot be cached aggressively, for example the product price and stock information. We would benefit from a separate API to load the stock and price information when the product will be (re)loaded in the same session, so that stock and price information can be updated. 

We could also consider to move into a query architecture, so that we would benefit from a graphQL architecture in the backend. This needs to be properly architected.

**Comment by giancorderoortiz** [comment] 2019-10-07 14:33
how to qa? measure perf improvement?

**Comment by giancorderoortiz** [comment] 2019-10-30 11:51
Any updates?

**Comment by dunqan** [comment] 2019-12-03 12:04
QA steps:
1. Carousel on home page should only load minimal product data (no categories, classifications, etc.)
2. Going from carousel product to product should display product data + load additional details 
3. Going directly to product page should result in one network call for the product (with merged fields)
4. Asking for a product a few times in a row, for different scopes, like:
```
    productService.get('2054947', ['list', 'details']).subscribe(x =>
      console.log('product!!', x)
    );
    productService.get('2054947', ['list']).subscribe(x =>
      console.log('product!!', x)
    );
    productService.get('2054947', ['details']).subscribe(x => console.log('product!!', x));
```
should result in only on one call for all of the scopes.

**Closed** 2019-12-03 19:57 UTC
Labels: performance

**Comment by psmul** [comment] 2020-01-09 09:11
QA steps performed and confirmed to be working as intended.
