### ISSUE TITLE
order history with order flow e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/cloud-commerce-spartacus-storefront#6151] opened 2020-01-20 04:44 UTC
mobile/my-account/order-history-orders-flow-mobile.e2e-spec.ts          

very similar to GH-6149 with the authorization error.

**Comment by bgambocjaviniar** [comment] 2020-01-21 05:59
this will be fix with GH-6151 (fails the same spot and place, where the doOrder function is not working and not having a placed order)

GH-6149 will be fixed with an update to a sample data user that we were using in dev-17.

**Comment by plabadie** [comment] 2020-01-22 20:07
Temporarily fixed in GH-6145:

Order history verification in the checkout flow test will be skipped when GH-6145 is merged.
So the tests will pass.
The skipped tests will need to be enabled when the backend issue is fixed.

**Comment by bgambocjaviniar** [comment] 2020-01-23 16:51
PR: GH-6233

Skipping the test because we have no solution to fix orders to be instantly set with oms

**Comment by hackergil** [comment] 2020-02-17 15:59
Failing in 1.5.x branch

**Comment by hackergil** [comment] 2020-02-17 17:20
Last failure from Jenkins was:

> Order History with orders should display placed order in Order History:
     CypressError: Timed out retrying: expected '<a.cx-order-history-value>' to contain '00016632'

They pass now. Let's see if they keep timing out.

**Comment by plabadie** [comment] 2020-02-19 19:06
Fails on 1.5.x
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/20/consoleText

**Comment by plabadie** [comment] 2020-02-21 22:59
PR 1.5.x: #6684 
Jemkins run: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/215/console

**Comment by plabadie** [comment] 2020-02-24 16:02
PRs:


Jenkins runs:
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/218/console
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/219/console

**Closed** 2020-02-28 19:32 UTC
Labels: 1.5-e2e, e2e-tests
