### ISSUE TITLE
subcategory menu is misplaced randomly

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#2122] opened 2019-04-24 15:18 UTC
**Environment Details**
Spartacus: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/
Browser: Chrome

**Steps to Reproduce**
Go to SPA
Click on a menu that opens, for eg, click on the arrow next to category "Digital Cameras"

**Actual Results**
The sub-categories are displayed somewhere else on the screen.

**Note**
This happens randomly. I cannot reproduce it on command. But I have seen this a few times. Haven't pinned down how it happens though. 

![misplacedCategoryMenu](https://user-images.githubusercontent.com/45409515/56671193-360b4280-6682-11e9-95a5-96d36c19d164.png)

<img width="765" alt="misplacedCategoryMenu1" src="https://user-images.githubusercontent.com/45409515/56671459-af0a9a00-6682-11e9-8a1b-3a3c64042c64.png">
<img width="1279" alt="misplacedCategoryMenu2" src="https://user-images.githubusercontent.com/45409515/56671460-af0a9a00-6682-11e9-938e-508737bafd48.png">

**Comment by Xymmer** [comment] 2019-04-25 20:51
dupe of #2014

**Closed** 2019-04-25 20:59 UTC
Labels: closed/duplicate, type/bug
