### ISSUE TITLE
Empty shopping cart shows duplicated and incorrect header

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/cloud-commerce-spartacus-storefront#3039] opened 2019-06-11 16:18 UTC
When there are no items in the shopping cart, the heading shows:

> Your Shopping Cart ()

The same is true for the page title tag. 

We should have a neutral heading, and could potentially avoid having duplicate headings as well

**Comment by Xymmer** [comment] 2019-06-11 16:28
closing as dupe of #2785 and #2910

**Closed by Xymmer** 2019-06-11 16:28 UTC
Labels: type/bug
