### ISSUE TITLE
Ipad Pro. Minor Misalignment Issues

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3167] opened 2019-06-13 16:14 UTC
Minor misalignment seen when doing exploratory testing on iPad Pro. 
Checkout steps, product list pages. 

OS: iOS 11.0.3.
Browser: Safari

See attached images. 

![iPadProMisalign4](https://user-images.githubusercontent.com/46171897/59449264-baea2100-8dd4-11e9-9852-63b8e6f4a99d.png)
![ipadProMisalign2](https://user-images.githubusercontent.com/46171897/59449278-c1789880-8dd4-11e9-82be-5a7ccb82da2e.jpeg)
![ipadProMisalign3](https://user-images.githubusercontent.com/46171897/59449279-c2112f00-8dd4-11e9-8324-4c240c3c2e63.jpeg)
![ipadProMisalignment](https://user-images.githubusercontent.com/46171897/59449280-c2112f00-8dd4-11e9-9834-512cbefd3c5e.jpeg)

**Comment by Xymmer** [comment] 2019-06-21 16:10
duplicate of other tickets

**Closed by Xymmer** 2019-06-21 16:10 UTC
Labels: type/bug, ux
