### ISSUE TITLE
Anynomous cart page

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/cloud-commerce-spartacus-storefront#2974] opened 2019-06-07 19:18 UTC
## Steps to Reproduce

Add an item to cart as an anonymous user, and without closing the page change the url to /cart

## Observed Results

no items in cart when we had 1 item

## Expected Results

I think it should still have 1 item in the cart even though we go through the cart page using the url. 

But maybe this is okay and just a feature since it is kind of similar like closing the browser and opening a new one which will make the item in the cart disappear.

**Comment by Xymmer** [comment] 2019-06-11 23:17
good catch but marking as stretch

**Comment by Xymmer** [comment] 2019-06-26 01:35
duplicate of existing refresh and lose cart ticket

**Closed by Xymmer** 2019-06-26 01:35 UTC
Labels: type/bug, type/improvement
