### ISSUE TITLE
Unable to deploy stock-notification branch localhost. Heap Issues. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5576] opened 2019-11-28 19:22 UTC
Unable to deploy branch feature/notification-preferences_my-interests_stock-notification in localhost. 
Upon start-up, I'm getting Javascript out of heap memory errors. 

Regarding #5123

**Comment by giancorderoortiz** [comment] 2019-11-28 19:23
![Screen Shot 2019-11-28 at 9 52 03 AM](https://user-images.githubusercontent.com/46171897/69828637-9ea73880-11ea-11ea-825a-2c07ae9c65d3.png)

**Comment by kate1zheng** [comment] 2019-12-02 07:31
Hi Giancarlo, thanks for your report. could you please write down the detailed info to help us reproduce the error?
- what's your OS?
- what's your JDK/Angular/SPA/.... version
- what's your local environment
- what's your steps to see the error

reproducing the error is the first step to resolve the issue.
because CI has passed, it seems that it is related with your local environment, we must know your environment clearly.

Thanks 
Kate

**Comment by giancorderoortiz** [comment] 2019-12-02 20:51
answers via slack

**Comment by KateChuen** [comment] 2019-12-11 19:22
Already merged.

**Closed** 2019-12-11 19:22 UTC
Labels: bug, stock-notification
