### ISSUE TITLE
[not related to promotions] Unable to Complete Checkout. Shipping Method Fails to Load. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#5632] opened 2019-12-03 17:38 UTC
**Steps to Reproduce:** 
1. Enable the following promotions in backoffice:
1.a. order_threshold_fixed_price_products_main (spend over $400 to get an infoLithium battery for $50). 
1.b. order_threshold_free_gift_main (spend over $500 and get a remote controlled tripod free). 
2. Navigate to Spartacus storefront. 
3. Add Miscellaneous products to cart. Subtotal should be higher than $400. 
4. Add specific sku: 482105 (lithium battery). 
5. Navigate to cart page. 
6. Confirm both promotions are shown in cart page. 
7. Proceed to checkout. 
8. Enter new shipping address (if not one stored already). 
9. Move on to shipping method step. 

**Expected Results:** 
6. As described. Both promotions clearly shown in cart page. 
9. User able to select shipping method. 

**Actual Results:** 
6. As described. Both promotions clearly shown in cart page. 
7. Miscellaneous error messages displayed. 
8. Spinner shown. Unable to select shipping method and complete checkout. 

_Promotions enabled in backend:_ 

![Screen Shot 2019-12-03 at 12 11 55 PM](https://user-images.githubusercontent.com/46171897/70075009-e8689800-15c9-11ea-84cd-a716ce8d5602.png)
![Screen Shot 2019-12-03 at 12 11 36 PM](https://user-images.githubusercontent.com/46171897/70075020-ed2d4c00-15c9-11ea-923d-f5c8e1c24327.png)

**Comment by giancorderoortiz** [comment] 2019-12-03 17:47
Actual behavior: 
![Screen Shot 2019-12-03 at 12 13 23 PM](https://user-images.githubusercontent.com/46171897/70075534-0256aa80-15cb-11ea-8feb-d92a6d3e443b.png)

![Screen Shot 2019-12-03 at 12 13 32 PM](https://user-images.githubusercontent.com/46171897/70075543-0682c800-15cb-11ea-8744-a17410bb2af4.png)

![Screen Shot 2019-12-03 at 12 13 43 PM](https://user-images.githubusercontent.com/46171897/70075551-097db880-15cb-11ea-910e-13d7704aab7d.png)

**Comment by qjimmy** [comment] 2019-12-03 18:03
The _payment-methods_ e2e tests have also caught this bug, see GH-5596

**Comment by KateChuen** [comment] 2019-12-03 18:07
Yes, and I see this issue even without promotions enabled.

**Comment by qjimmy** [comment] 2019-12-03 19:33
Marcin's change on branch `feature/GH-4432-counter-poc` fixes this problem.

**Comment by marlass** [comment] 2019-12-04 06:16
Mine change can fix some of the `object no longer valid` errors. As for the infinite loading, it is because of change in backend address structure. `shippingAddress` field is missing in address object returned after setting delivery address.

**Comment by Xymmer** [comment] 2019-12-04 21:03
Just to clarify, for this ticket, it's to fix the shipping address / infinite loading / new backend address structure problem.

**Comment by marlass** [comment] 2019-12-05 07:06
I was wrong about the backend address structure problem. It is correct. However I wasn't able to reproduce it even once. I could get one request to fail and throw the `object no longer valid` error, but I was always redirected to the delivery method step and I could complete checkout. I guess we need a combination of 2 requests failing to reproduce it. I will keep looking for a problem.

**Comment by marlass** [comment] 2019-12-05 09:53
Quickfix for this issue available here: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5664

Ticket for proper fix created: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5664

When checkout details requests fail then we have this infinite spinner. Quick fix just added retry mechanism.

**Comment by Xymmer** [comment] 2019-12-06 20:18
closing this one as the other issues take care of this one

**Closed by Xymmer** 2019-12-06 20:18 UTC
Labels: CRITICAL, P1, bug
