### ISSUE TITLE
Cancel Return Request: A confirmation message perhaps?

### ISSUE THREAD

**Issue by KateChuen** [SAP/cloud-commerce-spartacus-storefront#5862] opened 2019-12-17 16:45 UTC
**Environment Details**
Spartacus: epic/order-return-cancel branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Place an order
- Go to Order History
- Select a return request
- Click on "cancel return"

**ACTUAL RESULT**
The return is cancelled.

**Expected Result**
Would be nice to have a confirmation message before it happens? To make sure that is what the user wants to do? But worst case, he can resubmit another return request....

**Comment by Xymmer** [comment] 2019-12-17 18:29
yeah by design we just left it without a confirmation since you can just start a new return request
closing

**Closed by Xymmer** 2019-12-17 18:29 UTC
Labels: cancellations-returns
